In [17]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import image_dataset_from_directory

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773067442.239705 1477664 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [18]:
image_data_dir = "data/image_dataset"
image_dataset = image_dataset_from_directory(image_data_dir,
                                            labels="inferred",
                                            label_mode="binary",
                                            )
image_dataset

Found 8076 files belonging to 2 classes.

E0000 00:00:1773067448.073917 1477664 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

In [19]:
image_dataset

In [20]:
for sample in image_dataset.take(1):
    print(sample)

(<tf.Tensor: shape=(32, 256, 256, 3), dtype=float32, numpy=
array([[[[2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         ...,
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02]],

        [[2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         ...,
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02]],

        [[2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         ...,
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02],
         [2.55000000e+02, 2.55000000e+02, 2.55000000e+02]],

        ...,

        [[3.73593750e+01, 4.63593750e+01, 5.33593750e+01],
         [3.82634583e+01, 4.72634583e+01, 5.42634583e+01],
         [3.88214722e+01, 4.78214722e+01, 5.48214722e+01],
         ...,
         [3.28765869e+01, 4.18765869e+01, 4.88765869e+01],
         [3.35398560e+01, 4.25398560e+01, 4.95398560e+01],
         [3.80000000e+01, 4.70000000e+01, 5.40000000e+01]],

        [[3.34062500e+01, 4.24062500e+01, 4.94062500e+01],
         [3.63957520e+01, 4.53957520e+01, 5.23957520e+01],
         [3.83453979e+01, 4.73453979e+01, 5.43453979e+01],
         ...,
         [4.43063354e+01, 5.33063354e+01, 6.03063354e+01],
         [4.39548950e+01, 5.29548950e+01, 5.99548950e+01],
         [3.80000000e+01, 4.70000000e+01, 5.40000000e+01]],

        [[4.20000000e+01, 5.10000000e+01, 5.80000000e+01],
         [3.96855469e+01, 4.86855469e+01, 5.56855469e+01],
         [3.90000000e+01, 4.80000000e+01, 5.50000000e+01],
         ...,
         [4.15234375e+01, 5.05234375e+01, 5.75234375e+01],
         [4.26289062e+01, 5.16289062e+01, 5.86289062e+01],
         [3.80000000e+01, 4.70000000e+01, 5.40000000e+01]]],


       [[[1.27964844e+02, 1.30964844e+02, 1.13890625e+02],
         [1.55671875e+02, 1.58449219e+02, 1.39560547e+02],
         [1.77742188e+02, 1.78927734e+02, 1.60185547e+02],
         ...,
         [6.86386719e+01, 6.28242188e+01, 2.79375000e+01],
         [5.15585938e+01, 4.64472656e+01, 8.66992188e+00],
         [8.65898438e+01, 8.15898438e+01, 4.35898438e+01]],

        [[1.25612076e+02, 1.28612076e+02, 1.11537857e+02],
         [1.51474884e+02, 1.54315948e+02, 1.35236145e+02],
         [1.71807159e+02, 1.73140259e+02, 1.53105988e+02],
         ...,
         [6.90634003e+01, 6.32489471e+01, 2.83622284e+01],
         [5.05414810e+01, 4.59387093e+01, 8.16136551e+00],
         [8.59963379e+01, 8.10175781e+01, 4.30175781e+01]],

        [[1.25533554e+02, 1.28533554e+02, 1.10906425e+02],
         [1.48720337e+02, 1.51609009e+02, 1.32386353e+02],
         [1.66062836e+02, 1.67506195e+02, 1.46506195e+02],
         ...,
         [7.75326385e+01, 7.20793152e+01, 3.70120277e+01],
         [5.96068954e+01, 5.59584579e+01, 1.78940048e+01],
         [9.50379944e+01, 9.03728714e+01, 5.23622169e+01]],

        ...,

        [[8.61977997e+01, 7.11977997e+01, 4.81978035e+01],
         [9.91880264e+01, 8.41880264e+01, 6.14106827e+01],
         [1.25417023e+02, 1.10417023e+02, 8.97881165e+01],
         ...,
         [1.14158829e+02, 9.79010162e+01, 8.84166412e+01],
         [1.04293121e+02, 8.64044495e+01, 8.19591370e+01],
         [9.50200577e+01, 7.70200577e+01, 7.30200577e+01]],

        [[7.76597595e+01, 6.26597557e+01, 3.96597557e+01],
         [7.28738861e+01, 5.78738823e+01, 3.50965385e+01],
         [1.08563660e+02, 9.35636597e+01, 7.29347534e+01],
         ...,
         [1.23379433e+02, 1.07121620e+02, 9.75578766e+01],
         [1.08127510e+02, 9.02388382e+01, 8.57935257e+01],
         [9.50068512e+01, 7.70068512e+01, 7.30068512e+01]],

        [[9.28125000e+01, 7.78125000e+01, 5.48125000e+01],
         [6.60078125e+01, 5.10078125e+01, 2.82304688e+01],
         [1.03195312e+02, 8.81953125e+01, 6.75664062e+01],
         ...,
         [1.28742188e+02, 1.12484375e+02, 1.02814453e+02],
         [1.10226562e+02, 9.23378906e+01, 8.78925781e+01],
         [9.45195312e+01, 7.65195312e+01, 7.25195312e+01]]],


       [[[1.80000000e+01, 2.80000000e+01, 1.70000000e+01],
         [2.12500000e+01, 3.12500000e+01, 2.02500000e+01],
         [2.61250000e+01, 3.47500000e+01, 2.23750000e+01],
         ...,
         [3.63750000e+01, 3.34375000e+01, 1.62500000e+01],
         [3.48125000e+01, 2.98125000e+01, 6.50000000e+00],
         [3.40000000e+01, 2.90000000e+01, 0.00000000e+00]],

        [[2.37285156e+01, 3.37285156e+01, 2.27285156e+01],
         [2.29890137e+01, 3.29890137e+01, 2.19890137e+01],
         [2.30050049e+01, 3.16300049e+01, 1.92550049e+01],
         ...,
         [4.96733398e+01, 4.91909180e+01, 3.11850586e+01],
         [3.93646240e+01, 3.65128174e+01, 1.31491699e+01],
         [2.99082031e+01, 2.57265625e+01, 0.00000000e+00]],

        [[2.84863281e+01, 3.91835938e+01, 2.60917969e+01],
         [2.40286865e+01, 3.47259521e+01, 2.16341553e+01],
         [1.94362793e+01, 2.82791748e+01, 1.52504883e+01],
         ...,
         [4.53037109e+01, 4.65428467e+01, 2.85296631e+01],
         [3.76730957e+01, 3.61260986e+01, 1.49736328e+01],
         [2.96972656e+01, 2.70917969e+01, 4.88085938e+00]],

        ...,

        [[1.44992188e+02, 1.00992188e+02, 6.25976562e+01],
         [9.20733643e+01, 4.85653076e+01, 2.18218994e+01],
         [8.19990234e+01, 3.90838623e+01, 1.88641357e+01],
         ...,
         [1.61242676e+00, 8.76501465e+00, 1.78674316e+00],
         [1.69958496e+00, 1.15264893e+01, 4.09240723e+00],
         [0.00000000e+00, 1.13027344e+01, 3.69726562e+00]],

        [[9.87207031e+01, 5.56289062e+01, 1.93554688e+01],
         [1.15789551e+02, 7.41751709e+01, 3.67940674e+01],
         [1.43788330e+02, 1.02514893e+02, 6.47532959e+01],
         ...,
         [3.11059570e+00, 8.33728027e+00, 3.04248047e+00],
         [2.19104004e+00, 9.83825684e+00, 2.83300781e+00],
         [1.45312500e+00, 1.30898438e+01, 4.08984375e+00]],

        [[1.29000000e+02, 9.00000000e+01, 5.70000000e+01],
         [1.16812500e+02, 7.86250000e+01, 4.31875000e+01],
         [1.50437500e+02, 1.12437500e+02, 7.57500000e+01],
         ...,
         [1.71250000e+01, 2.50625000e+01, 1.67500000e+01],
         [1.20625000e+01, 2.20625000e+01, 1.30625000e+01],
         [8.00000000e+00, 1.80000000e+01, 9.00000000e+00]]],


       ...,


       [[[1.10000000e+01, 1.90000000e+01, 6.00000000e+00],
         [1.21171875e+01, 2.01171875e+01, 7.11718750e+00],
         [1.71953125e+01, 2.51953125e+01, 1.21953125e+01],
         ...,
         [8.95312500e+00, 1.09531250e+01, 7.95312500e+00],
         [8.17187500e+00, 1.01718750e+01, 7.17187500e+00],
         [8.00000000e+00, 1.00000000e+01, 7.00000000e+00]],

        [[1.19453125e+01, 1.97734375e+01, 6.85937500e+00],
         [1.30846558e+01, 2.09127808e+01, 7.99871826e+00],
         [1.82634888e+01, 2.60916138e+01, 1.31775513e+01],
         ...,
         [8.73626709e+00, 1.07362671e+01, 7.73626709e+00],
         [7.92144775e+00, 9.92144775e+00, 6.92144775e+00],
         [7.74218750e+00, 9.74218750e+00, 6.74218750e+00]],

        [[1.62421875e+01, 2.32890625e+01, 1.07656250e+01],
         [1.74822388e+01, 2.45291138e+01, 1.20056763e+01],
         [2.31188354e+01, 3.01657104e+01, 1.76422729e+01],
         ...,
         [7.75054932e+00, 9.75054932e+00, 6.75054932e+00],
         [6.78314209e+00, 8.78314209e+00, 5.78314209e+00],
         [6.57031250e+00, 8.57031250e+00, 5.57031250e+00]],

        ...,

        [[8.11562500e+01, 5.31562500e+01, 4.11562500e+01],
         [8.24285278e+01, 5.47722778e+01, 4.27722778e+01],
         [8.82116089e+01, 6.21178589e+01, 5.01178589e+01],
         ...,
         [8.02014160e+00, 4.02014160e+00, 1.24725342e+00],
         [7.96520996e+00, 3.96520996e+00, 1.00616455e+00],
         [7.95312500e+00, 3.95312500e+00, 9.53125000e-01]],

        [[6.70937500e+01, 3.90937500e+01, 2.70937500e+01],
         [6.88024292e+01, 4.11461792e+01, 2.91461792e+01],
         [7.65691528e+01, 5.04754028e+01, 3.84754028e+01],
         ...,
         [8.35583496e+00, 4.35583496e+00, 1.39678955e+00],
         [7.38537598e+00, 3.38537598e+00, 3.92761230e-01],
         [7.17187500e+00, 3.17187500e+00, 1.71875000e-01]],

        [[6.40000000e+01, 3.60000000e+01, 2.40000000e+01],
         [6.58046875e+01, 3.81484375e+01, 2.61484375e+01],
         [7.40078125e+01, 4.79140625e+01, 3.59140625e+01],
         ...,
         [8.42968750e+00, 4.42968750e+00, 1.42968750e+00],
         [7.25781250e+00, 3.25781250e+00, 2.57812500e-01],
         [7.00000000e+00, 3.00000000e+00, 0.00000000e+00]]],


       [[[7.60058594e+01, 7.30058594e+01, 6.40058594e+01],
         [7.62968750e+01, 7.32968750e+01, 6.42968750e+01],
         [3.65898438e+01, 3.35898438e+01, 2.45898438e+01],
         ...,
         [5.73808594e+01, 5.01757812e+01, 4.43222656e+01],
         [5.30703125e+01, 4.80351562e+01, 4.20351562e+01],
         [5.20058594e+01, 4.70058594e+01, 4.10058594e+01]],

        [[7.40360107e+01, 7.04030228e+01, 6.14030228e+01],
         [6.46692963e+01, 6.16581039e+01, 5.26581039e+01],
         [5.15328369e+01, 4.79147720e+01, 3.89147720e+01],
         ...,
         [7.03763885e+01, 6.19351807e+01, 5.54262924e+01],
         [7.01833725e+01, 6.38747787e+01, 5.66125336e+01],
         [7.23622055e+01, 6.48227921e+01, 5.81823425e+01]],

        [[7.36595612e+01, 6.84864502e+01, 5.90896072e+01],
         [5.18336182e+01, 4.84076385e+01, 3.86255112e+01],
         [6.01163864e+01, 5.49852066e+01, 4.55791168e+01],
         ...,
         [5.87841644e+01, 4.77112579e+01, 4.00162659e+01],
         [6.33353424e+01, 5.39399338e+01, 4.55560455e+01],
         [7.05440063e+01, 5.95807571e+01, 5.17881470e+01]],

        ...,

        [[2.36887741e+01, 1.17004929e+01, 1.36946335e+01],
         [3.32700424e+01, 2.32700424e+01, 2.42348862e+01],
         [3.77191010e+01, 2.77776947e+01, 2.67483978e+01],
         ...,
         [7.34826889e+01, 6.29099426e+01, 5.74444580e+01],
         [4.91051636e+01, 3.97166901e+01, 3.37273331e+01],
         [2.79115829e+01, 1.85443954e+01, 1.25443954e+01]],

        [[2.60351562e+01, 1.40468750e+01, 1.60410156e+01],
         [3.19824219e+01, 2.19824219e+01, 2.29472656e+01],
         [3.05019531e+01, 2.05605469e+01, 1.95312500e+01],
         ...,
         [2.93103027e+01, 2.09862823e+01, 1.55164566e+01],
         [2.59405060e+01, 2.03457031e+01, 1.47137909e+01],
         [2.59101562e+01, 2.03632812e+01, 1.47265625e+01]],

        [[2.60351562e+01, 1.40468750e+01, 1.60410156e+01],
         [3.19824219e+01, 2.19824219e+01, 2.29472656e+01],
         [3.05019531e+01, 2.05605469e+01, 1.95312500e+01],
         ...,
         [2.68828125e+01, 1.97949219e+01, 1.37070312e+01],
         [2.40527344e+01, 2.09824219e+01, 1.59648438e+01],
         [2.40000000e+01, 2.10000000e+01, 1.60000000e+01]]],


       [[[1.28035156e+02, 1.65035156e+02, 8.50351562e+01],
         [1.31175781e+02, 1.68175781e+02, 8.82812500e+01],
         [1.36351562e+02, 1.73292969e+02, 9.64687500e+01],
         ...,
         [1.06410156e+02, 1.30410156e+02, 8.24101562e+01],
         [1.01175781e+02, 1.25175781e+02, 7.71757812e+01],
         [9.80351562e+01, 1.22035156e+02, 7.40351562e+01]],

        [[1.26785156e+02, 1.63160156e+02, 8.81601562e+01],
         [1.29925781e+02, 1.66300781e+02, 9.13403320e+01],
         [1.35064941e+02, 1.71417969e+02, 9.76088867e+01],
         ...,
         [1.05196777e+02, 1.29196777e+02, 8.11967773e+01],
         [9.93227539e+01, 1.23322754e+02, 7.53227539e+01],
         [9.55424805e+01, 1.19542480e+02, 7.15424805e+01]],

        [[1.24910156e+02, 1.59789551e+02, 9.34013672e+01],
         [1.28077148e+02, 1.63300781e+02, 9.57612305e+01],
         [1.33917969e+02, 1.68417969e+02, 9.97050781e+01],
         ...,
         [1.04049805e+02, 1.29174805e+02, 8.00498047e+01],
         [9.85595703e+01, 1.23684570e+02, 7.45595703e+01],
         [9.55336914e+01, 1.20658691e+02, 7.15336914e+01]],

        ...,

        [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

        [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]],

        [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]]],
      shape=(32, 256, 256, 3), dtype=float32)>, <tf.Tensor: shape=(32, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.]], dtype=float32)>)

In [21]:
df.head()

NameError: name 'df' is not defined

In [22]:
pd.set_option('display.max_columns', None)

In [23]:
table_df_primary = pd.read_csv("data/table_dataset/primary_data.csv", delimiter=";")
table_df_secondary = pd.read_csv("data/table_dataset/secondary_data.csv", delimiter=";")

table_df_primary

,family,name,class,cap-diameter,cap-shape,Cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
0,Amanita Family,Fly Agaric,p,"[10, 20]","[x, f]","[g, h]","[e, o]",[f],[e],NaN,[w],"[15, 20]","[15, 20]",[s],[y],[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a, w]"
1,Amanita Family,Panther Cap,p,"[5, 10]","[p, x]",[g],[n],[f],[e],NaN,[w],"[6, 10]","[10, 20]",NaN,[y],[w],[u],[w],[t],[p],NaN,[d],"[u, a]"
2,Amanita Family,False Panther Cap,p,"[10, 15]","[x, f]",NaN,"[g, n]",[f],[e],NaN,[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[e, g]",NaN,[d],"[u, a]"
3,Amanita Family,The Blusher,e,"[5, 15]","[x, f]",NaN,[n],[t],NaN,NaN,[w],"[7, 15]","[10, 25]",[b],NaN,[w],[u],[w],[t],[g],NaN,[d],"[u, a]"
4,Amanita Family,Death Cap,p,"[5, 12]","[x, f]",[h],[r],[f],NaN,[c],[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Saddle-Cup Family,White Saddle,p,"[2, 6]",[o],NaN,[w],[f],[f],[f],[f],"[4, 7]","[20, 40]",NaN,[g],[w],NaN,NaN,[t],[f],NaN,"[p, d]","[u, a]"
169,Bracket Fungi,Elfin's Saddle,p,"[2, 4]",[o],NaN,"[g, k]",[f],[f],[f],[f],"[2, 5]","[10, 20]",NaN,[g],"[g, n]",NaN,NaN,[f],[f],NaN,[d],"[u, a]"
170,Bracket Fungi,Turban Fungus,p,"[5, 15]",[o],NaN,"[n, e]",[f],[f],[f],[f],"[2, 5]","[20, 30]",NaN,[g],[n],NaN,NaN,[f],[f],NaN,[d],"[s, u]"
171,Morel Family,Common Morel,e,"[3, 8]","[p, c, o]",NaN,"[n, g]",[f],[f],[f],[f],"[3, 8]","[15, 25]",NaN,NaN,[n],NaN,NaN,[f],[f],NaN,"[l, d]",[s]
172,Jelly Discs Family,Jelly Babies,p,"[1, 1.5]","[x, f, s]",[s],[y],[f],[f],[f],[f],"[2, 5]","[4, 7]",NaN,NaN,[y],NaN,NaN,[f],[f],NaN,[d],"[u, a]"

In [24]:
table_df_secondary

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,s,y,w,u,w,t,p,NaN,d,w
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61064,p,1.18,s,s,y,f,f,f,f,3.93,6.22,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61065,p,1.27,f,s,y,f,f,f,f,3.18,5.43,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61066,p,1.27,s,s,y,f,f,f,f,3.86,6.37,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61067,p,1.24,f,s,y,f,f,f,f,3.56,5.44,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61068,p,1.17,s,s,y,f,f,f,f,3.25,5.45,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u

# Pretrained model

In [25]:
import timm
import torch
import torchvision.transforms as T
from PIL import Image
from urllib.request import urlopen

In [42]:
model = timm.create_model("hf-hub:BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224", pretrained=True)
model = model.eval()

train_transforms = T.Compose([T.Resize((224, 224)), 
                              T.ToTensor(), 
                              T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]) 

img = Image.open("data/image_dataset/poisonous/Russula_emetica/Russula_emetica25.png")

output = model(train_transforms(img).unsqueeze(0))
output

tensor([[-3.8606, -0.9374,  2.6200,  ...,  0.8103, -2.3272,  2.0275]],
       grad_fn=<AddmmBackward0>)

In [43]:
import torch.nn.functional as F
# Get probabilities
probs = F.softmax(output, dim=1)
top5 = probs.topk(5)

# Get class labels from the model config
print(model.pretrained_cfg)  # check if label map is embedded

# Or access directly:
label_map = model.pretrained_cfg.get('label_map') or model.pretrained_cfg.get('classes')

# Top predictions
for prob, idx in zip(top5.values[0], top5.indices[0]):
    label = label_map[idx.item()] if label_map else idx.item()
    print(f"{label}: {prob.item():.4f}")

{'hf_hub_id': 'BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224', 'source': 'hf-hub', 'architecture': 'beit_base_patch16_224', 'custom_load': False, 'input_size': [3, 224, 224], 'fixed_input_size': False, 'interpolation': 'bicubic', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 2829, 'pool_size': None, 'first_conv': None, 'classifier': None}
2364: 0.9981
2346: 0.0017
2393: 0.0001
2382: 0.0000
2397: 0.0000

In [44]:
df_test = pd.read_csv("~/Downloads/FungiTastic-OpenSet-Test.csv")

In [46]:
df_test[df_test.category_id == 2364]

,eventDate,year,month,day,habitat,countryCode,scientificName,kingdom,phylum,class,order,family,genus,specificEpithet,hasCoordinate,species,iucnRedListCategory,substrate,latitude,longitude,coorUncert,observationID,region,district,filename,category_id,metaSubstrate,poisonous,captions
15245,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,0-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the centr...
15246,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,1-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the main ...
15247,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,2-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the main ...
23327,2023-08-11,2023.0,8.0,11.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,54.999977,15.063318,5.0,4465867600,Hovedstaden,Bornholm,0-4465867600.JPG,2364,jord,1,The image shows two distinct fungi with unique...
23328,2023-08-11,2023.0,8.0,11.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,54.999977,15.063318,5.0,4465867600,Hovedstaden,Bornholm,1-4465867600.JPG,2364,jord,1,The image shows two distinctive fungi growing ...
24894,2023-09-11,2023.0,9.0,11.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.070778,9.210778,15.0,4465879814,Midtjylland,Ikast-Brande,0-4465879814.JPG,2364,jord,1,The image shows two distinctive mushrooms in a...
26565,2023-10-12,2023.0,10.0,12.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.077130,15.023643,15.0,4465890050,Hovedstaden,Bornholm,0-4465890050.JPG,2364,jord,1,"The image shows a single, prominent mushroom a..."
26566,2023-10-12,2023.0,10.0,12.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.077130,15.023643,15.0,4465890050,Hovedstaden,Bornholm,1-4465890050.JPG,2364,jord,1,The image showcases a striking mushroom as the...
26944,2023-10-18,2023.0,10.0,18.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,57.291803,11.003939,15.0,4465897407,Nordjylland,Læsø,0-4465897407.JPG,2364,jord,1,The image shows a striking red fungus with a d...
56405,2023-10-18,2023.0,10.0,18.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.859750,8.238837,64.0,4465898340,NaN,NaN,0-4465898340.JPG,2364,jord,1,The image shows a striking mushroom lying on i...
56406,2023-10-18,2023.0,10.0,18.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.859750,8.238837,64.0,4465898340,NaN,NaN,1-4465898340.JPG,2364,jord,1,The image shows two distinct fungi on a forest...
56407,2023-10-18,2023.0,10.0,18.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.859750,8.238837,64.0,4465898340,NaN,NaN,2-4465898340.JPG,2364,jord,1,The image shows a striking mushroom lying on i...
56688,2023-10-21,2023.0,10.0,21.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.227208,10.695772,15.0,4465898521,Midtjylland,Syddjurs,0-4465898521.JPG,2364,jord,1,The image shows a striking mushroom as the cen...
56689,2023-10-21,2023.0,10.0,21.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.227208,10.695772,15.0,4465898521,Midtjylland,Syddjurs,1-4465898521.JPG,2364,jord,1,The image shows two distinct fungi with contra...
56690,2023-10-21,2023.0,10.0,21.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.227208,10.695772,15.0,4465898521,Midtjylland,Syddjurs,2-4465898521.JPG,2364,jord,1,The image shows a cluster of fungi with severa...
56691,2023-10-21,2023.0,10.0,21.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.227208,10.695772,15.0,4465898521,Midtjylland,Syddjurs,3-4465898521.JPG,2364,jord,1,The image shows two distinct fungi with contra...
65800,2023-10-13,2023.0,10.0,13.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.086437,14.977442,25.0,4465885112,Hovedstaden,Bornholm,0-4465885112.JPG,2364,jord,1,The image showcases a striking white mushroom ...
65801,2023-10-13,2023.0,10.0,13.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.086437,14.977442,25.0,4465885112,Hovedstaden,Bornholm,1-4465885112.JPG,2364,jord,1,The image showcases a striking red mushroom as...
82944,2023-08-28,2023.0,8.0,28.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.491613,8.440397,5.0,4465873394,Syddanmark,Esbjerg,0-4465873394.JPG,2364,jord,1,"The image shows a single, prominent fungus in ..."
82945,2023-08-28,2023.0,8.0,28.0,Mixed woodland (with coniferous and deciduous ...,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,55.491613,8.440397,5.0,4465873394,Syddanmark,Esbjerg,1-4465873394.JPG,2364,jord,1,The image shows a single mushroom as the main ...
87809,2023-09-21,2023.0,9.0,21.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.079886,9.315177,65.0,4847340801,Midtjylland,Silkeborg,0-4847340801.JPG,2364,jord,1,The image features a single mushroom as the fo...
92887,2023-09-03,2023.0,9.0,3.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.080028,9.368117,15.0,4465871568,Midtjylland,Silkeborg,0-4465871568.JPG,2364,jord,1,The image shows three Amanita muscaria mushroo...
92888,2023-09-03,2023.0,9.0,3.0,coniferous woodland/plantation,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.080028,9.368117,15.0,4465871568,Midtjylland,Silkeborg,1-4465871568.JPG,2364,jord,1,The image shows a striking mushroom with sever...