In [2]:
# For colab
!pip install pytest pylint ipdb jupyterlab numpy pandas matplotlib seaborn scikit-learn tensorflow timm transformers keras_hub

Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (8.4.2)
Requirement already satisfied: pylint in /usr/local/lib/python3.12/dist-packages (4.0.5)
Requirement already satisfied: ipdb in /usr/local/lib/python3.12/dist-packages (0.13.13)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/dist-packages (4.5.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (1.0.25)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: keras_hub in /usr/local/lib/python3.12/dist-packages (0.21.1)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.3.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from pytest) (26.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.19.2)
Requirement already satisfied: astroid<=4.1.dev0,>=4.0.2 in /usr/local/lib/python3.12/dist-packages (from pylint) (4.0.4)
Requirement already satisfied: dill>=0.3.6 in /usr/local/lib/python3.12/dist-packages (from pylint) (0.3.8)
Requirement already satisfied: isort!=5.13,<9,>=5 in /usr/local/lib/python3.12/dist-packages (from pylint) (8.0.1)
Requirement already satisfied: mccabe<0.8,>=0.6 in /usr/local/lib/python3.12/dist-packages (from pylint) (0.7.0)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pylint) (4.9.2)
Requirement already satisfied: tomlkit>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from pylint) (0.13.3)
Requirement already satisfied: ipython>=7.31.1 in /usr/local/lib/python3.12/dist-packages (from ipdb) (7.34.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipdb) (4.4.2)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.2.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (6.17.1)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.14.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (75.2.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (6.5.1)
Requirement already satisfied: traitlets in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from timm) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm) (0.25.0+cu128)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from timm) (6.0.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from timm) (1.5.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from timm) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras_hub) (13.9.4)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (from keras_hub) (0.3.13)
Requirement already satisfied: tensorflow-text in /usr/local/lib/python3.12/dist-packages (from keras_hub) (2.19.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (1.3.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (0.24.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (26.2.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (0.19.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (3.0.52)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.0.3->jupyterlab) (3.0.3)
Requirement already satisfied: argon2-cffi>=21.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.17.0)
Requirement already satisfied: nbformat>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.24.1)
Requirement already satisfied: send2trash>=1.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.9.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (4.26.0)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras_hub) (4.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->timm) (1.4.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.31.1->ipdb) (0.8.6)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.4)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab) (4.0.0)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras_hub) (0.1.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.3.0)

In [3]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import image_dataset_from_directory

In [4]:
image_data_dir = "data/image_dataset"
image_dataset = image_dataset_from_directory(image_data_dir,
                                            labels="inferred",
                                            label_mode="binary",
                                            )
image_dataset

NotFoundError: Could not find directory data/image_dataset

In [ ]:
image_dataset

In [ ]:
for sample in image_dataset.take(1):
    print(sample)

(<tf.Tensor: shape=(32, 256, 256, 3), dtype=float32, numpy=
array([[[[ 78.98242  ,  78.98242  ,  52.98242  ],
         [ 76.28125  ,  76.19336  ,  50.26367  ],
         [ 91.47266  ,  86.44336  ,  64.44336  ],
         ...,
         [ 84.37695  ,  77.14258  ,  59.054688 ],
         [ 72.19336  ,  69.12305  ,  54.070312 ],
         [ 65.041016 ,  62.041016 ,  47.041016 ]],

        [[ 66.30774  ,  65.0343   ,  39.67102  ],
         [ 73.74557  ,  72.406624 ,  47.102463 ],
         [ 89.67442  ,  84.64513  ,  62.645126 ],
         ...,
         [ 95.8752   ,  88.62217  ,  70.49697  ],
         [ 89.284035 ,  86.21372  ,  71.16099  ],
         [ 85.39736  ,  82.39736  ,  67.39736  ]],

        [[ 59.869858 ,  57.07617  ,  32.078484 ],
         [ 73.75212  ,  70.1282   ,  45.575462 ],
         [ 83.30994  ,  77.07393  ,  55.48002  ],
         ...,
         [117.30213  , 109.2494   ,  91.497444 ],
         [109.383125 , 106.29894  ,  91.25314  ],
         [102.95512  ,  99.95512  ,  84.95512  ]],

        ...,

        [[  3.0202484,   4.806999 ,   7.1945953],
         [  1.8589783,   3.2572174,   4.443161 ],
         [  4.4379807,   6.055008 ,   5.7854767],
         ...,
         [122.23063  , 131.79524  , 140.8068   ],
         [121.58877  , 131.78906  , 139.00458  ],
         [121.578125 , 131.78906  , 138.97266  ]],

        [[  5.3515625,   5.9882812,   7.984024 ],
         [  3.4399796,   4.0878906,   5.327751 ],
         [  7.9609375,   9.245018 ,   8.5177765],
         ...,
         [121.05859  , 131.38193  , 139.32402  ],
         [119.30379  , 131.00638  , 137.03996  ],
         [119.27344  , 131.       , 137.       ]],

        [[  5.9882812,   5.9882812,   7.9765625],
         [  4.0878906,   4.0878906,   4.0878906],
         [  9.234375 ,   9.263672 ,   9.1171875],
         ...,
         [121.05859  , 132.       , 138.08789  ],
         [118.052734 , 131.01758  , 137.01758  ],
         [118.       , 131.       , 137.       ]]],


       [[[ 60.       ,  45.       ,  42.       ],
         [ 60.085938 ,  45.085938 ,  42.085938 ],
         [ 60.476562 ,  45.476562 ,  42.476562 ],
         ...,
         [ 14.8671875,  27.867188 ,  17.867188 ],
         [  4.3203125,  17.320312 ,   7.3203125],
         [  2.       ,  15.       ,   5.       ]],

        [[ 59.054688 ,  44.054688 ,  41.054688 ],
         [ 59.155396 ,  44.155396 ,  41.140625 ],
         [ 59.61316  ,  44.61316  ,  41.53125  ],
         ...,
         [ 14.613403 ,  27.56842  ,  17.56842  ],
         [  4.133667 ,  17.055115 ,   7.0551147],
         [  1.828125 ,  14.7421875,   4.7421875]],

        [[ 54.757812 ,  39.757812 ,  36.757812 ],
         [ 54.92566  ,  39.92566  ,  36.84375  ],
         [ 55.6886   ,  40.6886   ,  37.234375 ],
         ...,
         [ 13.459839 ,  26.210388 ,  16.210388 ],
         [  3.2852783,  15.84967  ,   5.8496704],
         [  1.046875 ,  13.5703125,   3.5703125]],

        ...,

        [[ 42.046875 ,  32.046875 ,  22.046875 ],
         [ 42.210022 ,  32.210022 ,  22.210022 ],
         [ 42.9516   ,  32.9516   ,  22.9516   ],
         ...,
         [ 63.752197 ,  60.752197 ,  41.752197 ],
         [ 68.86694  ,  65.86694  ,  46.866943 ],
         [ 69.99219  ,  66.99219  ,  47.992188 ]],

        [[ 42.828125 ,  32.828125 ,  22.828125 ],
         [ 43.56195  ,  33.56195  ,  23.56195  ],
         [ 46.897522 ,  36.897522 ,  26.897522 ],
         ...,
         [ 71.21069  ,  68.21069  ,  49.210693 ],
         [ 76.93579  ,  73.93579  ,  54.93579  ],
         [ 78.19531  ,  75.19531  ,  56.195312 ]],

        [[ 43.       ,  33.       ,  23.       ],
         [ 43.859375 ,  33.859375 ,  23.859375 ],
         [ 47.765625 ,  37.765625 ,  27.765625 ],
         ...,
         [ 72.85156  ,  69.85156  ,  50.851562 ],
         [ 78.71094  ,  75.71094  ,  56.710938 ],
         [ 80.       ,  77.       ,  58.       ]]],


       [[[119.11719  ,  80.11719  ,  49.117188 ],
         [133.53125  ,  94.46094  ,  63.601562 ],
         [112.08594  ,  70.08594  ,  45.164062 ],
         ...,
         [232.80469  , 216.96094  , 218.       ],
         [236.90625  , 220.90625  , 221.90625  ],
         [239.97656  , 223.97656  , 224.97656  ]],

        [[126.155914 ,  87.155914 ,  56.155914 ],
         [145.03696  , 105.966644 ,  75.10727  ],
         [125.85498  ,  83.85498  ,  58.908234 ],
         ...,
         [235.32669  , 220.75638  , 221.15872  ],
         [240.07492  , 224.10477  , 225.08984  ],
         [242.52841  , 227.7919   , 228.16016  ]],

        [[134.08636  ,  96.26071  ,  64.86926  ],
         [151.53683  , 112.46652  ,  81.60715  ],
         [131.39615  ,  89.39615  ,  64.43521  ],
         ...,
         [236.0228   , 222.93729  , 222.97635  ],
         [241.47903  , 226.31497  , 226.90625  ],
         [243.1984   , 229.97183  , 229.97656  ]],

        ...,

        [[106.29483  ,  64.50577  ,  45.683197 ],
         [100.37213  ,  58.58307  ,  38.9776   ],
         [ 91.482666 ,  49.79538  ,  30.150848 ],
         ...,
         [ 63.1344   ,  44.52893  ,  29.923462 ],
         [ 68.4205   ,  47.655914 ,  33.641724 ],
         [ 97.32422  ,  78.70148  ,  64.10074  ]],

        [[101.97656  ,  60.976562 ,  40.25     ],
         [ 98.79547  ,  57.821014 ,  37.102966 ],
         [ 89.85794  ,  50.05078  ,  29.648438 ],
         ...,
         [ 49.546875 ,  29.457031 ,  14.8203125],
         [ 64.61859  ,  42.66336  ,  28.648438 ],
         [ 94.49432  ,  74.38956  ,  59.757812 ]],

        [[101.97656  ,  60.976562 ,  38.976562 ],
         [ 98.765625 ,  57.835938 ,  35.859375 ],
         [ 88.609375 ,  50.6875   ,  29.648438 ],
         ...,
         [ 50.820312 ,  28.820312 ,  14.8203125],
         [ 64.64844  ,  42.648438 ,  28.648438 ],
         [ 95.75781  ,  73.75781  ,  59.757812 ]]],


       ...,


       [[[254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         ...,
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ]],

        [[254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         ...,
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ]],

        [[254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         ...,
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ],
         [254.       , 254.       , 254.       ]],

        ...,

        [[238.74023  , 238.74023  , 240.74023  ],
         [253.18983  , 253.18983  , 249.8578   ],
         [244.33098  , 242.70207  , 231.372    ],
         ...,
         [253.       , 253.       , 255.       ],
         [253.       , 253.       , 255.       ],
         [253.       , 253.       , 255.       ]],

        [[240.52734  , 240.52734  , 242.52734  ],
         [253.16489  , 253.3888   , 249.83286  ],
         [244.38445  , 242.80229  , 231.42546  ],
         ...,
         [253.       , 253.       , 255.       ],
         [253.       , 253.       , 255.       ],
         [253.       , 253.       , 255.       ]],

        [[251.       , 251.       , 253.       ],
         [253.66602  , 254.55469  , 250.33398  ],
         [251.55664  , 250.11328  , 238.59766  ],
         ...,
         [253.       , 253.       , 255.       ],
         [253.       , 253.       , 255.       ],
         [253.       , 253.       , 255.       ]]],


       [[[ 52.       ,  91.       ,  44.       ],
         [ 53.804688 ,  92.71875  ,  45.71875  ],
         [ 62.007812 , 100.53125  ,  53.53125  ],
         ...,
         [ 44.421875 ,  71.421875 ,  38.421875 ],
         [ 51.453125 ,  78.453125 ,  45.453125 ],
         [ 53.       ,  80.       ,  47.       ]],

        [[ 54.0625   ,  92.80469  ,  45.890625 ],
         [ 55.852417 ,  94.51605  ,  47.61676  ],
         [ 63.988403 , 102.29498  ,  55.46283  ],
         ...,
         [ 44.59375  ,  71.421875 ,  38.507812 ],
         [ 51.625    ,  78.453125 ,  45.539062 ],
         [ 53.171875 ,  80.       ,  47.085938 ]],

        [[ 63.4375   , 101.00781  ,  54.484375 ],
         [ 65.16028  , 102.68561  ,  56.24408  ],
         [ 72.99109  , 110.31195  ,  64.24274  ],
         ...,
         [ 45.375    ,  71.421875 ,  38.898438 ],
         [ 52.40625  ,  78.453125 ,  45.929688 ],
         [ 53.953125 ,  80.       ,  47.476562 ]],

        ...,

        [[139.1875   , 186.1875   ,  84.1875   ],
         [138.7088   , 185.79474  ,  83.79474  ],
         [136.5329   , 184.00946  ,  82.00946  ],
         ...,
         [ 16.90625  ,   5.90625  ,   3.90625  ],
         [ 16.515625 ,   5.515625 ,   3.515625 ],
         [ 16.429688 ,   5.4296875,   3.4296875]],

        [[142.3125   , 189.3125   ,  87.3125   ],
         [141.7331   , 188.81903  ,  86.81903  ],
         [139.09943  , 186.57599  ,  84.57599  ],
         ...,
         [ 15.734375 ,   4.734375 ,   2.734375 ],
         [ 15.34375  ,   4.34375  ,   2.34375  ],
         [ 15.2578125,   4.2578125,   2.2578125]],

        [[143.       , 190.       ,  88.       ],
         [142.39844  , 189.48438  ,  87.484375 ],
         [139.66406  , 187.14062  ,  85.140625 ],
         ...,
         [ 15.4765625,   4.4765625,   2.4765625],
         [ 15.0859375,   4.0859375,   2.0859375],
         [ 15.       ,   4.       ,   2.       ]]],


       [[[ 73.48047  ,  69.48047  ,  44.48047  ],
         [ 56.214844 ,  52.214844 ,  27.548828 ],
         [ 34.34961  ,  30.34961  ,   7.7929688],
         ...,
         [112.83594  ,  96.578125 ,  72.28906  ],
         [107.66992  ,  88.89258  ,  50.228516 ],
         [ 87.70508  ,  68.70508  ,  28.705078 ]],

        [[ 94.52688  ,  90.018326 ,  67.81594  ],
         [ 75.16556  ,  72.11896  ,  48.597473 ],
         [ 59.246517 ,  54.992798 ,  33.793053 ],
         ...,
         [143.73828  , 128.37128  , 104.27111  ],
         [137.55515  , 120.36719  ,  85.39044  ],
         [117.46289  , 100.17969  ,  64.18555  ]],

        [[118.063034 , 113.73793  ,  95.06215  ],
         [ 98.10205  ,  96.08714  ,  74.856674 ],
         [ 81.392746 ,  77.41706  ,  58.720333 ],
         ...,
         [162.39864  , 149.07974  , 125.25702  ],
         [151.82155  , 137.2571   , 108.99144  ],
         [131.94247  , 117.37802  ,  88.68466  ]],

        ...,

        [[ 85.34057  ,  95.06412  ,  87.86702  ],
         [ 69.69234  ,  79.1357   ,  70.78876  ],
         [ 73.757416 ,  78.200775 ,  72.96054  ],
         ...,
         [ 42.13219  ,  37.57589  ,  19.682095 ],
         [ 51.36561  ,  44.959885 ,  30.509426 ],
         [ 40.6083   ,  34.043846 ,  21.26828  ]],

        [[109.80292  , 119.80292  , 111.322205 ],
         [ 82.7222   ,  92.16556  ,  82.69169  ],
         [ 77.03708  ,  81.5598   ,  75.23825  ],
         ...,
         [ 53.164112 ,  47.05083  ,  30.638382 ],
         [ 63.86077  ,  55.22796  ,  43.177177 ],
         [ 47.521515 ,  38.666046 ,  28.46317  ]],

        [[134.66406  , 144.66406  , 135.58984  ],
         [ 98.10742  , 107.55078  ,  96.99609  ],
         [ 83.927734 ,  88.55664  ,  81.55664  ],
         ...,
         [ 71.82422  ,  64.56641  ,  49.339844 ],
         [ 81.21875  ,  71.44141  ,  61.10742  ],
         [ 60.853516 ,  50.853516 ,  41.816406 ]]]],
      shape=(32, 256, 256, 3), dtype=float32)>, <tf.Tensor: shape=(32, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>)

2026-03-09 17:27:57.846408: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
table_df_primary = pd.read_csv("data/table_dataset/primary_data.csv", delimiter=";")
table_df_secondary = pd.read_csv("data/table_dataset/secondary_data.csv", delimiter=";")

table_df_primary

,family,name,class,cap-diameter,cap-shape,Cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
0,Amanita Family,Fly Agaric,p,"[10, 20]","[x, f]","[g, h]","[e, o]",[f],[e],NaN,[w],"[15, 20]","[15, 20]",[s],[y],[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a, w]"
1,Amanita Family,Panther Cap,p,"[5, 10]","[p, x]",[g],[n],[f],[e],NaN,[w],"[6, 10]","[10, 20]",NaN,[y],[w],[u],[w],[t],[p],NaN,[d],"[u, a]"
2,Amanita Family,False Panther Cap,p,"[10, 15]","[x, f]",NaN,"[g, n]",[f],[e],NaN,[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[e, g]",NaN,[d],"[u, a]"
3,Amanita Family,The Blusher,e,"[5, 15]","[x, f]",NaN,[n],[t],NaN,NaN,[w],"[7, 15]","[10, 25]",[b],NaN,[w],[u],[w],[t],[g],NaN,[d],"[u, a]"
4,Amanita Family,Death Cap,p,"[5, 12]","[x, f]",[h],[r],[f],NaN,[c],[w],"[10, 12]","[10, 20]",NaN,NaN,[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Saddle-Cup Family,White Saddle,p,"[2, 6]",[o],NaN,[w],[f],[f],[f],[f],"[4, 7]","[20, 40]",NaN,[g],[w],NaN,NaN,[t],[f],NaN,"[p, d]","[u, a]"
169,Bracket Fungi,Elfin's Saddle,p,"[2, 4]",[o],NaN,"[g, k]",[f],[f],[f],[f],"[2, 5]","[10, 20]",NaN,[g],"[g, n]",NaN,NaN,[f],[f],NaN,[d],"[u, a]"
170,Bracket Fungi,Turban Fungus,p,"[5, 15]",[o],NaN,"[n, e]",[f],[f],[f],[f],"[2, 5]","[20, 30]",NaN,[g],[n],NaN,NaN,[f],[f],NaN,[d],"[s, u]"
171,Morel Family,Common Morel,e,"[3, 8]","[p, c, o]",NaN,"[n, g]",[f],[f],[f],[f],"[3, 8]","[15, 25]",NaN,NaN,[n],NaN,NaN,[f],[f],NaN,"[l, d]",[s]
172,Jelly Discs Family,Jelly Babies,p,"[1, 1.5]","[x, f, s]",[s],[y],[f],[f],[f],[f],"[2, 5]","[4, 7]",NaN,NaN,[y],NaN,NaN,[f],[f],NaN,[d],"[u, a]"

In [ ]:
table_df_secondary

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,s,y,w,u,w,t,p,NaN,d,w
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61064,p,1.18,s,s,y,f,f,f,f,3.93,6.22,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61065,p,1.27,f,s,y,f,f,f,f,3.18,5.43,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61066,p,1.27,s,s,y,f,f,f,f,3.86,6.37,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61067,p,1.24,f,s,y,f,f,f,f,3.56,5.44,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61068,p,1.17,s,s,y,f,f,f,f,3.25,5.45,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u

# Pretrained model

In [ ]:
import timm
import torch
import torchvision.transforms as T
from PIL import Image
from urllib.request import urlopen

/home/clement/.pyenv/versions/kinoko/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
model = timm.create_model("hf-hub:BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224", pretrained=True)
model = model.eval()

train_transforms = T.Compose([T.Resize((224, 224)), 
                              T.ToTensor(), 
                              T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])]) 

img = Image.open("data/image_dataset/poisonous/Russula_emetica/Russula_emetica25.png")

output = model(train_transforms(img).unsqueeze(0))
output

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tensor([[-3.8606, -0.9374,  2.6200,  ...,  0.8103, -2.3272,  2.0275]],
       grad_fn=<AddmmBackward0>)

In [ ]:
import torch.nn.functional as F
# Get probabilities
probs = F.softmax(output, dim=1)
top5 = probs.topk(5)

# Get class labels from the model config
print(model.pretrained_cfg)  # check if label map is embedded

# Or access directly:
label_map = model.pretrained_cfg.get('label_map') or model.pretrained_cfg.get('classes')

# Top predictions
for prob, idx in zip(top5.values[0], top5.indices[0]):
    label = label_map[idx.item()] if label_map else idx.item()
    print(f"{label}: {prob.item():.4f}")

{'hf_hub_id': 'BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224', 'source': 'hf-hub', 'architecture': 'beit_base_patch16_224', 'custom_load': False, 'input_size': [3, 224, 224], 'fixed_input_size': False, 'interpolation': 'bicubic', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 2829, 'pool_size': None, 'first_conv': None, 'classifier': None}
2364: 0.9981
2346: 0.0017
2393: 0.0001
2382: 0.0000
2397: 0.0000

In [ ]:
df_test = pd.read_csv("~/Downloads/FungiTastic-OpenSet-Test.csv")

In [ ]:
df_test[df_test.category_id == 2364].head(1)

,eventDate,year,month,day,habitat,countryCode,scientificName,kingdom,phylum,class,order,family,genus,specificEpithet,hasCoordinate,species,iucnRedListCategory,substrate,latitude,longitude,coorUncert,observationID,region,district,filename,category_id,metaSubstrate,poisonous,captions
15245,2023-09-16,2023.0,9.0,16.0,heath,DK,Russula emetica (Schaeff.) Pers.,Fungi,Basidiomycota,Agaricomycetes,Russulales,Russulaceae,Russula,emetica,True,Russula emetica,NE,soil,56.067781,9.204794,15.0,4465878906,Midtjylland,Ikast-Brande,0-4465878906.JPG,2364,jord,1,The image shows a single mushroom as the centr...

## Fine tuning

In [ ]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

import keras
import keras_hub
import tensorflow as tf
import numpy as np

In [ ]:
# --- CONFIGURATION ---
# DINOv2 Base preset expects 518x518
IMG_SIZE = 518  
# NUM_CLASSES = 10 
BATCH_SIZE = 32
EPOCHS = 5
SEED = 42

In [ ]:
# --- 1. DATA PREPARATION ---

train_ds = tf.keras.utils.image_dataset_from_directory(
    image_data_dir,
    labels="inferred",
    label_mode="categorical", # Changed from 'binary' to match 10 classes
    validation_split=0.2,
    subset="training",
    seed=SEED,
    image_size=(IMG_SIZE, IMG_SIZE), # Changed to 518
    batch_size=BATCH_SIZE
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    image_data_dir,
    labels="inferred",
    label_mode="categorical", # Changed from 'binary'
    validation_split=0.2,
    subset="validation",
    seed=SEED,
    image_size=(IMG_SIZE, IMG_SIZE), # Changed to 518
    batch_size=BATCH_SIZE
)

Found 8076 files belonging to 2 classes.
Using 6461 files for training.
Found 8076 files belonging to 2 classes.
Using 1615 files for validation.

In [ ]:
# --- 2. MODEL BUILDING ---

backbone = keras_hub.models.DINOV2Backbone.from_preset("dinov2_base")

# Freeze the backbone
backbone.trainable = False

# Build the model
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

# ImageNet Normalization
x = keras.layers.Rescaling(1/255.0)(inputs)
x = keras.layers.Normalization(
    mean=[0.485, 0.456, 0.406], 
    variance=[0.229**2, 0.224**2, 0.225**2]
)(x)

# Pass to backbone
outputs = backbone(x)[:, 0, :]

In [ ]:
# --- 3. CUSTOM HEAD ---
x = keras.layers.Dense(512, activation="relu")(outputs)
# x = keras.layers.BatchNormalization()(x)
# x = keras.layers.Dropout(0.3)(x)
# x = keras.layers.Dense(256, activation="relu")(x)
predictions = keras.layers.Dense(2, activation="softmax")(x)

model = keras.Model(inputs=inputs, outputs=predictions)

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy", "recall", "precision"]
)

model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_10 (InputLayer)     │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ rescaling_10 (Rescaling)        │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ normalization_10                │ (None, 518, 518, 3)    │             0 │
│ (Normalization)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dinov2_backbone                 │ (None, 1370, 768)      │    87,632,640 │
│ (DINOV2Backbone)                │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ get_item_3 (GetItem)            │ (None, 768)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 512)            │       393,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 2)              │         1,026 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,027,394 (335.80 MB)

 Trainable params: 394,754 (1.51 MB)

 Non-trainable params: 87,632,640 (334.29 MB)

In [ ]:
# --- 4. TRAINING ---
print("\nStarting training...")
model.fit(
    train_ds,
    validation_data=test_ds,
    epochs=EPOCHS
)

Starting training...
Epoch 1/5

/home/clement/.pyenv/versions/kinoko/lib/python3.12/site-packages/keras/src/models/functional.py:241: UserWarning: The structure of `inputs` doesn't match the expected structure.
Expected: {'images': 'images'}
Received: inputs=Tensor(shape=(None, 518, 518, 3))
  warnings.warn(msg)
2026-03-10 09:32:02.995010: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:84] Allocation of 2882918400 exceeds 10% of free system memory.

In [ ]:
# # --- 5. OPTIONAL: FULL FINE-TUNING ---
# # After the head is trained, you can unfreeze and train with a tiny learning rate
# print("\nUnfreezing backbone for fine-tuning...")
# backbone.trainable = True
# model.compile(
#     optimizer=keras.optimizers.Adam(learning_rate=1e-6), # Extremely low LR
#     loss="categorical_crossentropy",
#     metrics=["accuracy"]
# )
# # model.fit(train_ds, validation_data=val_ds, epochs=2)

# # --- 6. EVALUATION & PREDICTION ---
# print("\nEvaluating model...")
# loss, accuracy = model.evaluate(val_ds)
# print(f"Validation Accuracy: {accuracy*100:.2f}%")

# # Prediction example
# sample_img = np.random.rand(1, IMG_SIZE, IMG_SIZE, 3).astype("float32")
# prediction = model.predict(sample_img)
# print(f"Prediction shape: {prediction.shape}")

In [ ]:
outputs