In [2]:
# For colab
!pip install pytest pylint ipdb jupyterlab numpy pandas matplotlib seaborn scikit-learn tensorflow timm transformers keras_hub==0.26.0

Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (8.4.2)
Requirement already satisfied: pylint in /usr/local/lib/python3.12/dist-packages (4.0.5)
Requirement already satisfied: ipdb in /usr/local/lib/python3.12/dist-packages (0.13.13)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/dist-packages (4.5.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (1.0.25)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: keras_hub==0.26.0 in /usr/local/lib/python3.12/dist-packages (0.26.0)
Requirement already satisfied: keras>=3.13 in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (3.13.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (1.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (26.0)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (2025.11.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (13.9.4)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (0.3.13)
Requirement already satisfied: tensorflow-text in /usr/local/lib/python3.12/dist-packages (from keras_hub==0.26.0) (2.19.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.19.2)
Requirement already satisfied: astroid<=4.1.dev0,>=4.0.2 in /usr/local/lib/python3.12/dist-packages (from pylint) (4.0.4)
Requirement already satisfied: dill>=0.3.6 in /usr/local/lib/python3.12/dist-packages (from pylint) (0.3.8)
Requirement already satisfied: isort!=5.13,<9,>=5 in /usr/local/lib/python3.12/dist-packages (from pylint) (8.0.1)
Requirement already satisfied: mccabe<0.8,>=0.6 in /usr/local/lib/python3.12/dist-packages (from pylint) (0.7.0)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pylint) (4.9.2)
Requirement already satisfied: tomlkit>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from pylint) (0.13.3)
Requirement already satisfied: ipython>=7.31.1 in /usr/local/lib/python3.12/dist-packages (from ipdb) (7.34.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipdb) (4.4.2)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.2.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (6.17.1)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.14.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (75.2.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (6.5.1)
Requirement already satisfied: traitlets in /usr/local/lib/python3.12/dist-packages (from jupyterlab) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from timm) (2.10.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from timm) (0.25.0+cu128)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from timm) (6.0.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from timm) (1.5.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from timm) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (1.3.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm) (0.24.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.1)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (26.2.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (0.19.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (3.0.52)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.31.1->ipdb) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.0.3->jupyterlab) (3.0.3)
Requirement already satisfied: argon2-cffi>=21.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.4)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.17.0)
Requirement already satisfied: nbformat>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.24.1)
Requirement already satisfied: send2trash>=1.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.9.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (4.26.0)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.13->keras_hub==0.26.0) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.13->keras_hub==0.26.0) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras_hub==0.26.0) (4.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->timm) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->timm) (1.4.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.31.1->ipdb) (0.8.6)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.30.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.4)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab) (4.0.0)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras_hub==0.26.0) (0.1.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.3.0)

In [3]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils import image_dataset_from_directory

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [11]:
image_data_dir = "/content/drive/MyDrive/Colab Notebooks/lewagon/Kinoko/data/image_dataset"
image_dataset = image_dataset_from_directory(image_data_dir,
                                            labels="inferred",
                                            label_mode="binary",
                                            )
image_dataset

Found 7972 files belonging to 2 classes.

In [4]:
for sample in image_dataset.take(1):
    print(sample)

NameError: name 'image_dataset' is not defined

In [12]:
pd.set_option('display.max_columns', None)

In [ ]:
#table_df_primary = pd.read_csv("data/table_dataset/primary_data.csv", delimiter=";")
#table_df_secondary = pd.read_csv("data/table_dataset/secondary_data.csv", delimiter=";")

table_df_primary = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/lewagon/Kinoko/data/table_dataset/primary_data.csv", delimiter=";")
table_df_secondary = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/lewagon/Kinoko/data/table_dataset/secondary_data.csv", delimiter=";")

table_df_primary

,family,name,class,cap-diameter,cap-shape,Cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,...,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,Spore-print-color,habitat,season
0,Amanita Family,Fly Agaric,p,"[10, 20]","[x, f]","[g, h]","[e, o]",[f],[e],NaN,...,[s],[y],[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a, w]"
1,Amanita Family,Panther Cap,p,"[5, 10]","[p, x]",[g],[n],[f],[e],NaN,...,NaN,[y],[w],[u],[w],[t],[p],NaN,[d],"[u, a]"
2,Amanita Family,False Panther Cap,p,"[10, 15]","[x, f]",NaN,"[g, n]",[f],[e],NaN,...,NaN,NaN,[w],[u],[w],[t],"[e, g]",NaN,[d],"[u, a]"
3,Amanita Family,The Blusher,e,"[5, 15]","[x, f]",NaN,[n],[t],NaN,NaN,...,[b],NaN,[w],[u],[w],[t],[g],NaN,[d],"[u, a]"
4,Amanita Family,Death Cap,p,"[5, 12]","[x, f]",[h],[r],[f],NaN,[c],...,NaN,NaN,[w],[u],[w],[t],"[g, p]",NaN,[d],"[u, a]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,Saddle-Cup Family,White Saddle,p,"[2, 6]",[o],NaN,[w],[f],[f],[f],...,NaN,[g],[w],NaN,NaN,[t],[f],NaN,"[p, d]","[u, a]"
169,Bracket Fungi,Elfin's Saddle,p,"[2, 4]",[o],NaN,"[g, k]",[f],[f],[f],...,NaN,[g],"[g, n]",NaN,NaN,[f],[f],NaN,[d],"[u, a]"
170,Bracket Fungi,Turban Fungus,p,"[5, 15]",[o],NaN,"[n, e]",[f],[f],[f],...,NaN,[g],[n],NaN,NaN,[f],[f],NaN,[d],"[s, u]"
171,Morel Family,Common Morel,e,"[3, 8]","[p, c, o]",NaN,"[n, g]",[f],[f],[f],...,NaN,NaN,[n],NaN,NaN,[f],[f],NaN,"[l, d]",[s]
172,Jelly Discs Family,Jelly Babies,p,"[1, 1.5]","[x, f, s]",[s],[y],[f],[f],[f],...,NaN,NaN,[y],NaN,NaN,[f],[f],NaN,[d],"[u, a]"

In [ ]:
table_df_secondary

,class,cap-diameter,cap-shape,cap-surface,cap-color,does-bruise-or-bleed,gill-attachment,gill-spacing,gill-color,stem-height,stem-width,stem-root,stem-surface,stem-color,veil-type,veil-color,has-ring,ring-type,spore-print-color,habitat,season
0,p,15.26,x,g,o,f,e,NaN,w,16.95,17.09,s,y,w,u,w,t,g,NaN,d,w
1,p,16.60,x,g,o,f,e,NaN,w,17.99,18.19,s,y,w,u,w,t,g,NaN,d,u
2,p,14.07,x,g,o,f,e,NaN,w,17.80,17.74,s,y,w,u,w,t,g,NaN,d,w
3,p,14.17,f,h,e,f,e,NaN,w,15.77,15.98,s,y,w,u,w,t,p,NaN,d,w
4,p,14.64,x,h,o,f,e,NaN,w,16.53,17.20,s,y,w,u,w,t,p,NaN,d,w
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61064,p,1.18,s,s,y,f,f,f,f,3.93,6.22,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61065,p,1.27,f,s,y,f,f,f,f,3.18,5.43,NaN,NaN,y,NaN,NaN,f,f,NaN,d,a
61066,p,1.27,s,s,y,f,f,f,f,3.86,6.37,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61067,p,1.24,f,s,y,f,f,f,f,3.56,5.44,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u
61068,p,1.17,s,s,y,f,f,f,f,3.25,5.45,NaN,NaN,y,NaN,NaN,f,f,NaN,d,u

# Pretrained model

In [13]:
import timm
import torch
import torchvision.transforms as T
from PIL import Image
from urllib.request import urlopen

In [14]:
model = timm.create_model("hf-hub:BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224", pretrained=True)
model = model.eval()

train_transforms = T.Compose([T.Resize((224, 224)),
                              T.ToTensor(),
                              T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])])

img = Image.open("/content/drive/MyDrive/Colab Notebooks/lewagon/Kinoko/data/image_dataset/poisonous/Helvella_crispa/Helvella_crispa25.png")
#img = Image.open("data/image_dataset/poisonous/Russula_emetica/Russula_emetica25.png")

output = model(train_transforms(img).unsqueeze(0))
output

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/155 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/352M [00:00<?, ?B/s]

KeyboardInterrupt:

In [ ]:
import torch.nn.functional as F
# Get probabilities
probs = F.softmax(output, dim=1)
top5 = probs.topk(5)

# Get class labels from the model config
print(model.pretrained_cfg)  # check if label map is embedded

# Or access directly:
label_map = model.pretrained_cfg.get('label_map') or model.pretrained_cfg.get('classes')

# Top predictions
for prob, idx in zip(top5.values[0], top5.indices[0]):
    label = label_map[idx.item()] if label_map else idx.item()
    print(f"{label}: {prob.item():.4f}")

{'hf_hub_id': 'BVRA/beit_base_patch16_224.in1k_ft_fungitastic_224', 'source': 'hf-hub', 'architecture': 'beit_base_patch16_224', 'custom_load': False, 'input_size': [3, 224, 224], 'fixed_input_size': False, 'interpolation': 'bicubic', 'crop_pct': 0.875, 'crop_mode': 'center', 'mean': (0.485, 0.456, 0.406), 'std': (0.229, 0.224, 0.225), 'num_classes': 2829, 'pool_size': None, 'first_conv': None, 'classifier': None}
1074: 0.9958
1078: 0.0040
1075: 0.0001
1854: 0.0000
1040: 0.0000

In [ ]:
df_test = pd.read_csv("~/Downloads/FungiTastic-OpenSet-Test.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/root/Downloads/FungiTastic-OpenSet-Test.csv'

In [ ]:
df_test[df_test.category_id == 1074].head(1)

## Fine tuning

In [15]:
import os
os.environ["KERAS_BACKEND"] = "tensorflow"

import keras
import keras_hub
import tensorflow as tf
import numpy as np

In [16]:
# --- CONFIGURATION ---
# DINOv2 Base preset expects 518x518
IMG_SIZE = 518
BATCH_SIZE = 32
EPOCHS = 50
SEED = 42

In [17]:
# --- DATA PREPARATION ---

train_ds = tf.keras.utils.image_dataset_from_directory(
    image_data_dir,
    labels="inferred",
    label_mode="binary",
    validation_split=0.3,
    subset="training",
    seed=SEED,
    image_size=(IMG_SIZE, IMG_SIZE), # Changed to 518
    batch_size=BATCH_SIZE
)

test_val_ds = tf.keras.utils.image_dataset_from_directory(
    image_data_dir,
    labels="inferred",
    label_mode="binary",
    validation_split=0.3,
    subset="validation",
    seed=SEED,
    image_size=(IMG_SIZE, IMG_SIZE), # Changed to 518
    batch_size=BATCH_SIZE
)

# Split test and val data
half_test_val_size = int(len(test_val_ds)/2)
test_ds = test_val_ds.take(half_test_val_size)
val_ds = test_val_ds.skip(half_test_val_size)

# Prefect for faster loading in gpu
train_ds.prefetch(tf.data.AUTOTUNE)
test_ds.prefetch(tf.data.AUTOTUNE)
val_ds.prefetch(tf.data.AUTOTUNE)

Found 7972 files belonging to 2 classes.
Using 5581 files for training.
Found 7972 files belonging to 2 classes.
Using 2391 files for validation.

In [18]:
# --- MODEL BUILDING ---

backbone = keras_hub.models.DINOV2Backbone.from_preset("dinov2_base")

# Freeze the backbone
backbone.trainable = False

# Build the model
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

# ImageNet Normalization
x = keras.layers.Rescaling(1/255.0)(inputs)
x = keras.layers.Normalization(
    mean=[0.485, 0.456, 0.406],
    variance=[0.229**2, 0.224**2, 0.225**2]
)(x)

# Pass to backbone
#backbone_out = backbone({"images": x})
#outputs = backbone(backbone_out)[:, 0, :]
backbone_out = backbone({"images": x})  # ← dict
outputs = backbone_out[:, 0, :]  # CLS token

Downloading from https://www.kaggle.com/api/v1/models/keras/dinov2/keras/dinov2_base/1/download/config.json...

100%|██████████| 781/781 [00:00<00:00, 1.56MB/s]

Downloading from https://www.kaggle.com/api/v1/models/keras/dinov2/keras/dinov2_base/1/download/model.weights.h5...

  0%|          | 0.00/335M [00:00<?, ?B/s]
  0%|          | 1.00M/335M [00:01<07:46, 750kB/s]
  1%|          | 2.00M/335M [00:01<04:11, 1.39MB/s]
  1%|          | 3.00M/335M [00:01<02:49, 2.06MB/s]
  1%|          | 4.00M/335M [00:02<02:07, 2.72MB/s]
  2%|▏         | 6.00M/335M [00:02<01:18, 4.37MB/s]
  2%|▏         | 8.00M/335M [00:02<00:58, 5.88MB/s]
  3%|▎         | 11.0M/335M [00:02<00:40, 8.45MB/s]
  4%|▍         | 14.0M/335M [00:02<00:28, 11.8MB/s]
  5%|▍         | 16.0M/335M [00:02<00:27, 12.2MB/s]
  6%|▌         | 19.0M/335M [00:03<00:24, 13.6MB/s]
  7%|▋         | 22.0M/335M [00:03<00:22, 14.3MB/s]
  7%|▋         | 25.0M/335M [00:03<00:19, 17.0MB/s]
  8%|▊         | 27.0M/335M [00:03<00:20, 16.0MB/s]
  9%|▉         | 30.0M/335M [00:03<00:19, 16.3MB/s]
 10%|▉         | 33.0M/335M [00:04<00:21, 14.5MB/s]
 10%|█         | 35.0M/335M [00:04<00:24, 12.9MB/s]
 12%|█▏        | 39.0M/335M [00:04<00:21, 14.7MB/s]
 13%|█▎        | 43.0M/335M [00:04<00:19, 15.9MB/s]
 14%|█▎        | 46.0M/335M [00:04<00:19, 15.7MB/s]
 15%|█▍        | 50.0M/335M [00:05<00:18, 15.9MB/s]
 16%|█▌        | 53.0M/335M [00:05<00:18, 15.6MB/s]
 17%|█▋        | 57.0M/335M [00:05<00:17, 16.5MB/s]
 18%|█▊        | 60.0M/335M [00:05<00:17, 16.1MB/s]
 19%|█▉        | 64.0M/335M [00:06<00:16, 16.9MB/s]
 20%|██        | 68.0M/335M [00:06<00:16, 17.4MB/s]
 21%|██        | 71.0M/335M [00:06<00:16, 16.8MB/s]
 22%|██▏       | 75.0M/335M [00:06<00:15, 17.4MB/s]
 24%|██▎       | 79.0M/335M [00:06<00:15, 17.8MB/s]
 24%|██▍       | 82.0M/335M [00:07<00:15, 17.1MB/s]
 26%|██▌       | 86.0M/335M [00:07<00:14, 17.6MB/s]
 27%|██▋       | 90.0M/335M [00:07<00:14, 18.0MB/s]
 28%|██▊       | 93.0M/335M [00:07<00:14, 17.3MB/s]
 29%|██▉       | 97.0M/335M [00:08<00:14, 17.7MB/s]
 30%|███       | 101M/335M [00:08<00:13, 18.0MB/s]
 31%|███       | 104M/335M [00:08<00:13, 17.3MB/s]
 32%|███▏      | 108M/335M [00:08<00:13, 17.8MB/s]
 33%|███▎      | 111M/335M [00:08<00:13, 17.1MB/s]
 34%|███▍      | 115M/335M [00:09<00:13, 17.6MB/s]
 36%|███▌      | 119M/335M [00:09<00:12, 18.0MB/s]
 36%|███▋      | 122M/335M [00:09<00:12, 17.3MB/s]
 38%|███▊      | 126M/335M [00:09<00:12, 17.7MB/s]
 39%|███▉      | 130M/335M [00:10<00:11, 18.0MB/s]
 40%|███▉      | 133M/335M [00:10<00:12, 17.3MB/s]
 41%|████      | 137M/335M [00:10<00:11, 17.8MB/s]
 42%|████▏     | 140M/335M [00:10<00:11, 17.1MB/s]
 43%|████▎     | 144M/335M [00:10<00:11, 17.6MB/s]
 44%|████▍     | 148M/335M [00:11<00:10, 17.9MB/s]
 45%|████▌     | 151M/335M [00:11<00:11, 17.3MB/s]
 46%|████▋     | 155M/335M [00:11<00:10, 17.7MB/s]
 47%|████▋     | 159M/335M [00:11<00:10, 18.0MB/s]
 48%|████▊     | 162M/335M [00:11<00:10, 17.3MB/s]
 50%|████▉     | 166M/335M [00:12<00:09, 17.7MB/s]
 51%|█████     | 170M/335M [00:12<00:09, 18.1MB/s]
 52%|█████▏    | 173M/335M [00:12<00:09, 17.3MB/s]
 53%|█████▎    | 177M/335M [00:12<00:09, 17.6MB/s]
 54%|█████▍    | 180M/335M [00:13<00:09, 17.1MB/s]
 55%|█████▍    | 184M/335M [00:13<00:09, 17.4MB/s]
 56%|█████▌    | 187M/335M [00:13<00:07, 19.6MB/s]
 57%|█████▋    | 190M/335M [00:13<00:07, 19.4MB/s]
 57%|█████▋    | 192M/335M [00:13<00:08, 17.1MB/s]
 58%|█████▊    | 195M/335M [00:13<00:08, 17.0MB/s]
 59%|█████▉    | 199M/335M [00:14<00:08, 17.6MB/s]
 60%|██████    | 202M/335M [00:14<00:08, 16.9MB/s]
 62%|██████▏   | 206M/335M [00:14<00:07, 17.4MB/s]
 63%|██████▎   | 210M/335M [00:14<00:07, 18.0MB/s]
 64%|██████▎   | 213M/335M [00:14<00:07, 17.2MB/s]
 65%|██████▍   | 217M/335M [00:15<00:06, 17.8MB/s]
 66%|██████▌   | 220M/335M [00:15<00:07, 17.1MB/s]
 67%|██████▋   | 224M/335M [00:15<00:06, 17.6MB/s]
 68%|██████▊   | 228M/335M [00:15<00:06, 17.9MB/s]
 69%|██████▉   | 231M/335M [00:16<00:06, 17.3MB/s]
 70%|███████   | 235M/335M [00:16<00:06, 16.9MB/s]
 71%|███████   | 238M/335M [00:16<00:06, 16.4MB/s]
 72%|███████▏  | 241M/335M [00:16<00:06, 16.1MB/s]
 73%|███████▎  | 245M/335M [00:16<00:05, 16.9MB/s]
 74%|███████▍  | 249M/335M [00:17<00:05, 17.5MB/s]
 75%|███████▌  | 252M/335M [00:17<00:05, 16.9MB/s]
 76%|███████▋  | 256M/335M [00:17<00:04, 17.5MB/s]
 78%|███████▊  | 260M/335M [00:17<00:04, 17.9MB/s]
 79%|███████▊  | 263M/335M [00:18<00:04, 17.2MB/s]
 80%|███████▉  | 267M/335M [00:18<00:04, 17.7MB/s]
 81%|████████  | 271M/335M [00:18<00:03, 18.0MB/s]
 82%|████████▏ | 274M/335M [00:18<00:03, 17.3MB/s]
 83%|████████▎ | 278M/335M [00:18<00:03, 17.8MB/s]
 84%|████████▍ | 281M/335M [00:19<00:03, 17.1MB/s]
 85%|████████▌ | 285M/335M [00:19<00:02, 17.6MB/s]
 86%|████████▋ | 289M/335M [00:19<00:02, 18.0MB/s]
 87%|████████▋ | 292M/335M [00:19<00:02, 17.3MB/s]
 88%|████████▊ | 296M/335M [00:19<00:02, 17.7MB/s]
 90%|████████▉ | 300M/335M [00:20<00:02, 18.1MB/s]
 91%|█████████ | 303M/335M [00:20<00:01, 17.3MB/s]
 92%|█████████▏| 307M/335M [00:20<00:01, 17.8MB/s]
 93%|█████████▎| 311M/335M [00:20<00:01, 18.1MB/s]
 94%|█████████▍| 314M/335M [00:21<00:01, 17.3MB/s]
 95%|█████████▍| 318M/335M [00:21<00:00, 17.8MB/s]
 96%|█████████▌| 321M/335M [00:21<00:00, 17.1MB/s]
 97%|█████████▋| 325M/335M [00:21<00:00, 17.6MB/s]
 98%|█████████▊| 329M/335M [00:21<00:00, 18.0MB/s]
100%|██████████| 335M/335M [00:22<00:00, 15.8MB/s]

In [19]:
# --- CUSTOM HEAD ---
x = keras.layers.Dense(512, activation="relu")(outputs)
# x = keras.layers.BatchNormalization()(x)
x = keras.layers.Dropout(0.3)(x)
# x = keras.layers.Dense(256, activation="relu")(x)
predictions = keras.layers.Dense(1, activation="sigmoid")(x)

model = keras.Model(inputs=inputs, outputs=predictions)

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss="binary_crossentropy",
    metrics=["accuracy", "recall", "precision"]
)

model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ rescaling (Rescaling)           │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ normalization (Normalization)   │ (None, 518, 518, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dinov2_backbone                 │ (None, 1370, 768)      │    87,632,640 │
│ (DINOV2Backbone)                │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ get_item (GetItem)              │ (None, 768)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 512)            │       393,728 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 512)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           513 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 88,026,881 (335.80 MB)

 Trainable params: 394,241 (1.50 MB)

 Non-trainable params: 87,632,640 (334.29 MB)

In [20]:
from google.colab import auth
auth.authenticate_user()

In [24]:
# --- CALLBACKS ---
callbacks = [
    # Stop early if val_loss stops improving
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    ),

    # Save the best checkpoint
    keras.callbacks.ModelCheckpoint(
        filepath="best_model.keras",
        monitor="val_loss",
        save_best_only=True
    ),

    # Reduce LR on plateau (helps squeeze out last gains)
    keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-7
    ),

    keras.callbacks.ModelCheckpoint(
      filepath="/content/drive/MyDrive/Colab Notebooks/lewagon/Kinoko/checkpoints/dinov2_epoch_{epoch:02d}.keras",
      save_best_only=True,
      save_freq="epoch",  # every N epochs, or "epoch" for every one
    ),
#    keras.callbacks.ModelCheckpoint(
#        filepath="gs://bucket_of_mushrooms/checkpoints/dinov2_epoch_{epoch:02d}.keras",
#        save_best_only=True,
#        save_freq=3,
#    )
]

In [25]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# --- TRAINING ---
print("\nStarting training...")
model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=callbacks
)

Starting training...
Epoch 1/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 3415s 20s/step - accuracy: 0.7529 - loss: 0.5560 - precision: 0.7990 - recall: 0.8573 - val_accuracy: 0.8326 - val_loss: 0.3745 - val_precision: 0.8436 - val_recall: 0.9396 - learning_rate: 1.0000e-04
Epoch 2/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1489s 9s/step - accuracy: 0.8352 - loss: 0.3857 - precision: 0.8601 - recall: 0.9088 - val_accuracy: 0.8633 - val_loss: 0.3325 - val_precision: 0.8794 - val_recall: 0.9358 - learning_rate: 1.0000e-04
Epoch 3/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1355s 8s/step - accuracy: 0.8565 - loss: 0.3270 - precision: 0.8778 - recall: 0.9200 - val_accuracy: 0.8732 - val_loss: 0.2967 - val_precision: 0.8925 - val_recall: 0.9350 - learning_rate: 1.0000e-04
Epoch 4/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1347s 8s/step - accuracy: 0.8853 - loss: 0.2751 - precision: 0.8962 - recall: 0.9428 - val_accuracy: 0.8807 - val_loss: 0.2834 - val_precision: 0.9007 - val_recall: 0.9379 - learning_rate: 1.0000e-04
Epoch 5/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1440s 8s/step - accuracy: 0.9029 - loss: 0.2404 - precision: 0.9120 - recall: 0.9509 - val_accuracy: 0.8873 - val_loss: 0.2727 - val_precision: 0.8979 - val_recall: 0.9484 - learning_rate: 1.0000e-04
Epoch 6/50
 45/175 ━━━━━━━━━━━━━━━━━━━━ 14:25 7s/step - accuracy: 0.9091 - loss: 0.2350 - precision: 0.9203 - recall: 0.9448

In [ ]:
# # --- 5. OPTIONAL: FULL FINE-TUNING ---
# # After the head is trained, you can unfreeze and train with a tiny learning rate
# print("\nUnfreezing backbone for fine-tuning...")
# backbone.trainable = True
# model.compile(
#     optimizer=keras.optimizers.Adam(learning_rate=1e-6), # Extremely low LR
#     loss="categorical_crossentropy",
#     metrics=["accuracy"]
# )
# # model.fit(train_ds, validation_data=val_ds, epochs=2)

# # --- 6. EVALUATION & PREDICTION ---
# print("\nEvaluating model...")
# loss, accuracy = model.evaluate(val_ds)
# print(f"Validation Accuracy: {accuracy*100:.2f}%")

# # Prediction example
# sample_img = np.random.rand(1, IMG_SIZE, IMG_SIZE, 3).astype("float32")
# prediction = model.predict(sample_img)
# print(f"Prediction shape: {prediction.shape}")